### ISSUE TITLE
Smooth, but a having issue at simple injector?

### ISSUE THREAD

**Issue by weedkiller** [akasarto/aspnet-mvc5-starter-template#9] opened 2018-11-29 18:54 UTC
Hi, this is very very nice  😁 
reading your help, I was able to run app.cmd install from power shell, but when I run the app. 

1. - Couple of things I get this error `SimpleInjector.SimpleInjectorMvcExtensions.RegisterMvcIntegratedFilterProvider..`

__________________________________________
```
System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Web.Mvc, Version=5.2.6.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 
The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=SimpleInjector.Integration.Web.Mvc
  StackTrace:
   at SimpleInjector.SimpleInjectorMvcExtensions.RegisterMvcIntegratedFilterProvider(Container container)
   at App.UI.Mvc5.Initializer.GetContainer() in C:\aspnet-mvc5-sarto\sources\App.UI.Mvc5\Initializer.cs:line 72
   at App.UI.Mvc5.Initializer.ConfigureDependencyInjectionContainer(IAppBuilder appBuilder) in C:\aspnet-mvc5-sarto\sources\App.UI.Mvc5\Initializer.cs:line 89
   at App.UI.Mvc5.Initializer.Initialize(IAppBuilder appBuilder) in C:\aspnet-mvc5-sarto\sources\App.UI.Mvc5\Initializer.cs:line 56

Inner Exception 1:
FileLoadException: Could not load file or assembly 'System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```
____________

2. -  also its complaining about a ref to Linq, should I ignore that or how do I fix that.
![image](https://user-images.githubusercontent.com/21086190/49244602-2ee74d80-f3de-11e8-961b-496eefd2eed1.png)

**Comment by akasarto** [comment] 2018-12-08 02:40
This problem is caused by outdated assembly bindings in *web.config* file. It was fixed in the last commit: 9a87a065fcd9eeab112734c7bb4d298231f2da32

**Closed by akasarto** 2018-12-08 02:40 UTC
Labels: bug
